/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'error-container': '#ffdad6',
        'on-surface': '#191c1d',
        'inverse-surface': '#2e3132',
        'surface-container': '#edeeef',
        'secondary-fixed-dim': '#44dfab',
        background: '#f8f9fa',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#001a40',
        'surface-variant': '#e1e3e4',
        'on-secondary-fixed': '#002116',
        'secondary-container': '#67fcc6',
        'tertiary-container': '#983c00',
        'on-secondary-fixed-variant': '#00513a',
        'on-surface-variant': '#424752',
        'surface-bright': '#f8f9fa',
        'on-error-container': '#93000a',
        'primary-fixed': '#d7e2ff',
        surface: '#f8f9fa',
        'surface-tint': '#115cb9',
        'on-secondary-container': '#007354',
        'on-tertiary-container': '#ffc2a7',
        'surface-container-highest': '#e1e3e4',
        secondary: '#006c4f',
        'on-tertiary-fixed': '#351000',
        'on-primary-fixed-variant': '#004491',
        'tertiary-fixed': '#ffdbcc',
        'tertiary-fixed-dim': '#ffb694',
        error: '#ba1a1a',
        'surface-container-high': '#e7e8e9',
        'on-primary-container': '#bbd0ff',
        'surface-dim': '#d9dadb',
        primary: '#003f87',
        'inverse-on-surface': '#f0f1f2',
        'primary-container': '#0056b3',
        'outline-variant': '#c2c6d4',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed-variant': '#7b2f00',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#acc7ff',
        'inverse-primary': '#acc7ff',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-background': '#191c1d',
        'surface-container-low': '#f3f4f5',
        outline: '#727784',
        tertiary: '#722b00',
        'secondary-fixed': '#67fcc6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'container-max': '1440px',
        base: '8px',
        gutter: '24px',
        'margin-desktop': '32px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'body-md': ['Inter'],
        'headline-md': ['Inter'],
        'body-lg': ['Inter'],
        'display-lg': ['Inter'],
        'headline-lg': ['Inter'],
        'label-sm': ['Inter'],
        'label-md': ['Inter'],
        'headline-lg-mobile': ['Inter'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
